name: organon-syl
version: 0.1.0.0
github: "dmatysiak/organon-syl"
license: BSD-3-Clause
author: "Daniel A. Matysiak"
copyright: "2026 Daniel A. Matysiak"

extra-source-files:
  - README.md
  - CHANGELOG.md

category: Theorem Provers, Logic, Formal Methods
synopsis: A proof assistant for medieval syllogistic logic.

description: Please see the README on GitHub at <https://github.com/dmatysiak/organon-syl#readme>

language: GHC2021

dependencies:
  - base >= 4.7 && < 5
  - text
  - megaparsec
  - parser-combinators
  - haskeline
  - containers
  - lsp
  - lsp-types
  - co-log-core
  - stm
  - directory
  - filepath

default-extensions:
  - DerivingStrategies
  - DuplicateRecordFields
  - OverloadedStrings
  - StrictData

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  organon-syl-repl:
    main: Main.hs
    source-dirs: app/repl
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - organon-syl

  organon-syl-lsp:
    main: Main.hs
    source-dirs: app/lsp
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - organon-syl

  organon-syl-check:
    main: Main.hs
    source-dirs: app/check
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - organon-syl

tests:
  organon-syl-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - organon-syl
      - hspec
      - text
