name:                organon
version:             0.1.0.0
github:              "dmatysiak/organon"
license:             BSD3
author:              "Daniel A. Matysiak"
#maintainer:          "example@example.com"
copyright:           "2018 Daniel A. Matysiak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dmatysiak/organon#readme>

dependencies:
- base >= 4.7 && < 5
- containers == 0.5.11.0
- optparse-applicative == 0.14.2.0
- readline == 1.0.3.0
- parsec == 3.1.13.0

library:
  source-dirs: src

executables:
  organon:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - organon

tests:
  organon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - organon
